### PR TITLE
Basic functionality switchboard

### PR DESCRIPTION
**Pull request by fehlmach**
Basic functionality switchboard

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/2)

### CODE REVIEW

**Comment by britram** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 12 unresolved discussions.

---

*[rainsd/inbox.go, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7TsCotn-AFFURbvNl:-Kf7TsCotn-AFFURbvNm:beh6iuj) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/inbox.go#L1)):*
> ```Go
> package rainsd
> ```

(not reviewing this, since it's the next step, but marked OK)

---

*[rainsd/server.conf, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7HIJtKef7F6zDL5V2:-Kf7HIJu2rOG-FATqICP:b-fichfm) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/server.conf#L1)):*
> ```
> {
> ```

We should probably create a subdirectory for testing and configuration files.

---

*[rainsd/serverUtil.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7Nsm_drrZmNDi6ZMM:-Kf7NsmasMhodvWT0aB7:bmb55eb) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/serverUtil.go#L26)):*
> ```Go
> //type 1 contains IPAddr and Port information
> type ConnInfo struct {
> 	Type   int
> ```

This should be an enumerated type, instead of a magic integer. See https://golang.org/ref/spec#Iota

---

*[rainsd/serverUtil.go, line 40 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7KerBPovOw1yr6bFw:-Kf7KerCysNJy0pW0tL2:b-sftma9) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/serverUtil.go#L40)):*
> ```Go
> 	return strconv.Itoa(int(c.Port))
> }
> ```

These aren't really server utilities: RainsMessage and the rest of the data model belongs in rainslib.

---

*[rainsd/switchboard.go, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7TXq0o6HCcvxkYmZX:-Kf7TXq1RrWGFFz2TcUv:b-6rqsyn) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L1)):*
> ```Go
> //The switchboard listens for incoming connections from servers or clients,
> ```

This seems like a mostly sane design.

---

*[rainsd/switchboard.go, line 24 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7L56yuV3k6ms1fNnM:-Kf7L56yuV3k6ms1fNnN:b4lfpu0) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L24)):*
> ```Go
> )
> 
> const (
> ```

FYI obviously we should load this from a file too :)

---

*[rainsd/switchboard.go, line 89 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7LEi0NyIkkf_l-s2k:-Kf7LEi0NyIkkf_l-s2l:btyf1sg) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L89)):*
> ```Go
> 
> //TODO CFE periodically send heartbeat to all server connections (store ConnInfo of servers in a different cache and look up writer in the active cache)
> ```

FYI you can also use TLS keepalive (which I'm not sure is implemented in Go; Google is your friend) or TCP keepalive to provide the same functionality.

---

*[rainsd/switchboard.go, line 92 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7OA1qYUXzGNvllp_G:-Kf7OA1r45drIx6-uDdU:bkrox5k) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L92)):*
> ```Go
> //SendTo sends the given message to the specified receiver.
> //TODO CFE replace string with RainsMessage
> func SendTo(message string, receiver ConnInfo) {
> ```

Nope, this should actually take a `[]byte`. Switchboard's job is moving chunks of data around. `RainsMessage` should be able to turn itself into the appropriate flavor of `[]byte`.

---

*[rainsd/switchboard.go, line 118 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7Mcv1zKKVswZn1ovu:-Kf7Mcv1zKKVswZn1ovv:b-dh5akm) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L118)):*
> ```Go
> 
> //creatConnection establishes a connection based on the type and data of the ConnInfo
> func creatConnection(receiver ConnInfo) (net.Conn, error) {
> ```

is this a UNIX API pun (`$ man 2 creat`) or a typo?

---

*[rainsd/switchboard.go, line 139 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7QpsIFP9suYa3SfQB:-Kf7QpsIFP9suYa3SfQC:b-ys76fo) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L139)):*
> ```Go
> }
> 
> //TODO CFE replace string with RainsMessage
> ```

See above. Switchboard deals in byte slices.

---

*[rainsd/switchboard.go, line 145 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7Qu8aEsH_fyyI2UiF:-Kf7Qu8aEsH_fyyI2UiG:b-ys76fo) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L145)):*
> ```Go
> 
> //deframe reads a framed message from r and returns the transformed message
> //TODO CFE replace string with RainsMessage
> ```

See above. Switchboard deals in byte slices.

---

*[rainsd/switchboard.go, line 184 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7TM8XgxyaDBUMOMIR:-Kf7TM8YeSl-8OZAi6br:b-6afee0) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L184)):*
> ```Go
> //handleConnection passes all incoming messages to the inbox which processes them.
> func handleConnection(conn net.Conn, client ConnInfo) {
> 	scan := bufio.NewScanner(bufio.NewReader(conn))
> ```

This will need a pluggable scanner when we do CBOR. But that's probably after August.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2)*

**Comment by fehlmach** [comment]
Review status: 6 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[rainsd/switchboard.go, line 24 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7L56yuV3k6ms1fNnM:-KfAkjPZouc1LFnvi3gG:bjim4br) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L24)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

FYI obviously we should load this from a file too :)
</blockquote></details>

yes, I already changed that but I forgot to delete it before I pushed it;-)

---

*[rainsd/switchboard.go, line 118 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7Mcv1zKKVswZn1ovu:-KfB-o_gXCuNarf3lrpA:bb7phvt) ([raw file](https://github.com/netsec-ethz/rains/blob/096bdf936eb569b3c9e0b0fe0f1f7bd85393d889/rainsd/switchboard.go#L118)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

is this a UNIX API pun (`$ man 2 creat`) or a typo?
</blockquote></details>

typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2)*

**Comment by fehlmach** [comment]
Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[rainsd/server.conf, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7HIJtKef7F6zDL5V2:-KfBsVH7hDLiCx-_NegG:b-hz2tuw) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/server.conf#L1)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

We should probably create a subdirectory for testing and configuration files.
</blockquote></details>

I created a subdirectory for configuratoin files.
But I leave the test files in the same directory because otherwise I could only test public function, if I am not mistaken.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2)*

**Comment by fehlmach** [comment]
Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[rainsd/serverUtil.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7Nsm_drrZmNDi6ZMM:-KfBuFB2KrVunBQV3meW:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/serverUtil.go#L26)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

This should be an enumerated type, instead of a magic integer. See https://golang.org/ref/spec#Iota
</blockquote></details>

Done.

---

*[rainsd/serverUtil.go, line 40 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7KerBPovOw1yr6bFw:-KfBuPScYxmA4q6NHH9e:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/serverUtil.go#L40)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

These aren't really server utilities: RainsMessage and the rest of the data model belongs in rainslib.
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 92 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7OA1qYUXzGNvllp_G:-KfBuSbN0RXnMmGPqbHB:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/switchboard.go#L92)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

Nope, this should actually take a `[]byte`. Switchboard's job is moving chunks of data around. `RainsMessage` should be able to turn itself into the appropriate flavor of `[]byte`.
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 118 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7Mcv1zKKVswZn1ovu:-KfBuT1j8K4VcqoJX3iz:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/switchboard.go#L118)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 139 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7QpsIFP9suYa3SfQB:-KfBuTOVey1QMBtOZRiq:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/switchboard.go#L139)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

See above. Switchboard deals in byte slices.
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 145 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7Qu8aEsH_fyyI2UiF:-KfBuT_L6AY6Ap_67Vu3:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/switchboard.go#L145)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

See above. Switchboard deals in byte slices.
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 184 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7TM8XgxyaDBUMOMIR:-KfBuU-d13_DE0LX_hRo:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/switchboard.go#L184)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

This will need a pluggable scanner when we do CBOR. But that's probably after August.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2)*

**Comment by klausman** [comment]
Reviewed 2 of 10 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[rainsd/serverUtil.go, line 38 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfBxWKPq1D5aIvOra7r:-KfBxWKPq1D5aIvOra7s:b-k3i82l) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/serverUtil.go#L38)):*
> ```Go
> 	Type   ProtocolType
> 	IPAddr string
> 	Port   uint
> ```

This should be a uint16.

---

*[rainsd/serverUtil.go, line 58 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfBy3xGhEg40GG7F9FX:-KfBy3xH5_Z12yo165eI:b-2911w5) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/serverUtil.go#L58)):*
> ```Go
> 	file, err := ioutil.ReadFile(configPath)
> 	if err != nil {
> 		log.Fatal(err)
> ```

This should log what's going on ("Couldn't open config file...") and the filename.

---

*[rainsd/switchboard.go, line 72 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfBzxZa92nOTuxZv8cf:-KfBzxZa92nOTuxZv8cg:b-afz7gd) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L72)):*
> ```Go
> 	serverConnInfo, err = getIPAddrandPort()
> 	if err != nil {
> 		log.Error("error", err)
> ```

This should have a more descriptive error message. Also, you can switch to `log.Fatal()` and drop the `panic()`

The first part is true of all log statements (I won't comment on them individually).

---

*[rainsd/switchboard.go, line 140 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC-v4_E0uGqtB_V6MA:-KfC-v4_E0uGqtB_V6MB:b91ha4l) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L140)):*
> ```Go
> 	switch receiver.Type {
> 	case TCP:
> 		tcp := "tcp"
> ```

This variable is never changed and used exactly once, you should drop it and just use the literal below.

---

*[rainsd/switchboard.go, line 155 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC09Gveu3mr4n8E3zv:-KfC09GwgsJWKwUEFQXM:b-34fkra) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L155)):*
> ```Go
> 	switch client.Type {
> 	case TCP:
> 		return client.IPAddr + sep + client.PortToString() + sep + server.IPAddr + sep + server.PortToString()
> ```

This would look cleaner as `return fmt.Sprintf("%s_%i_%s_%i", client.IPAddr, client.Port, server.IPAddr, server.Port)`

---

*[rainsd/switchboard.go, line 167 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC0rAIdm_CXnhxU-uL:-KfC0rAIdm_CXnhxU-uM:bzbsvu3) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L167)):*
> ```Go
> 	srvLogger := log.New("addr", addrAndport)
> 
> 	cer, err := tls.LoadX509KeyPair(Config.CertificateFile, Config.PrivateKeyFile)
> ```

Shouldn't this be `cert`?

---

*[rainsd/switchboard.go, line 214 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC1Ahe24YvTI-vsVeu:-KfC1Ahf7FYIdbWU3uUI:bqdehyd) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L214)):*
> ```Go
> //getIPAddrandPort fetches HostAddr and port number from config file on which this server is listening to
> func getIPAddrandPort() (ConnInfo, error) {
> 	if Config.ServerIPAddr == "" || Config.ServerPort == 0 {
> ```

This should not be fatal but default to listening on all addresses and some port we pick.

---

*[rainsd/verify.go, line 3 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC1ZXpjtoXy-UIPeoQ:-KfC1ZXqFf-0hTUpME-Z:bmrrqha) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/verify.go#L3)):*
> ```Go
> package rainsd
> 
> type cipherSuit string
> ```

`cipherSuite`

---

*[rainsd/server.conf, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7HIJtKef7F6zDL5V2:-KfC2IFXwKDSdw9lvmsf:b-3hv8ec) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/server.conf#L1)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

I created a subdirectory for configuratoin files.
But I leave the test files in the same directory because otherwise I could only test public function, if I am not mistaken.
</blockquote></details>

I think we shouldn't have cert+key in the repository: someone will check out the codebase and use those files in production, either by accident or due to incompetence. We could include a small script that generates a self-signed cert+key for testing purposes and then `.gitignore` those locations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[rainsd/serverUtil.go, line 38 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfBxWKPq1D5aIvOra7r:-KfC6Gra3nhXG4HGQIHq:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/serverUtil.go#L38)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This should be a uint16.
</blockquote></details>

Done.

---

*[rainsd/serverUtil.go, line 58 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfBy3xGhEg40GG7F9FX:-KfC6ae3HoQL9kC3RZWL:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/serverUtil.go#L58)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This should log what's going on ("Couldn't open config file...") and the filename.
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 72 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfBzxZa92nOTuxZv8cf:-KfCAhmJqNVSc2Bc_XBe:b2lkdxd) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L72)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This should have a more descriptive error message. Also, you can switch to `log.Fatal()` and drop the `panic()`

The first part is true of all log statements (I won't comment on them individually).
</blockquote></details>

I want to have a centralized init function, but for now I just have it here to be able to test this code. After that i will report the error back to main() which will handle it or logs the error and exits.

---

*[rainsd/switchboard.go, line 140 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC-v4_E0uGqtB_V6MA:-KfC80XldUuuZAFD8ZYy:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L140)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This variable is never changed and used exactly once, you should drop it and just use the literal below.
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 155 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC09Gveu3mr4n8E3zv:-KfCAQIi7TgX50fRG9MY:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L155)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This would look cleaner as `return fmt.Sprintf("%s_%i_%s_%i", client.IPAddr, client.Port, server.IPAddr, server.Port)`
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 167 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC0rAIdm_CXnhxU-uL:-KfCATeXJEBtfWOQUNYj:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L167)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Shouldn't this be `cert`?
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 214 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC1Ahe24YvTI-vsVeu:-KfCB_KE8SVCJDkgOejD:bcrcd0a) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L214)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This should not be fatal but default to listening on all addresses and some port we pick.
</blockquote></details>

I am not sure if it is a good idea to allow a RAINS server listen on all addresses. Then there is no incentive to change it as it runs perfectly until it breaks due to incoming messages on a lot of possible addresses which otherwise do not bother this server. (e.g. when an attack is happening on another address, this server would also be affected)
To pick a default port might be an option. Do we want to have a default values for all config values hard coded?

---

*[rainsd/verify.go, line 3 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC1ZXpjtoXy-UIPeoQ:-KfCDCRGfMmQCFpqyDXg:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/verify.go#L3)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

`cipherSuite`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[rainsd/switchboard.go, line 72 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfBzxZa92nOTuxZv8cf:-KfCGSuKRVBnqf6W95xO:bb75wk5) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L72)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

I want to have a centralized init function, but for now I just have it here to be able to test this code. After that i will report the error back to main() which will handle it or logs the error and exits.
</blockquote></details>

WFM.

---

*[rainsd/switchboard.go, line 214 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC1Ahe24YvTI-vsVeu:-KfCGeXnhZRSDb9_diQy:b-pfbx24) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L214)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

I am not sure if it is a good idea to allow a RAINS server listen on all addresses. Then there is no incentive to change it as it runs perfectly until it breaks due to incoming messages on a lot of possible addresses which otherwise do not bother this server. (e.g. when an attack is happening on another address, this server would also be affected)
To pick a default port might be an option. Do we want to have a default values for all config values hard coded?
</blockquote></details>

Hard code them for now. We can later decide which ones have no default and must always be user-supplied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-:-KfCGyuMRGd4yTRZ3Pqc:bnfp4nl)*

**Comment by britram** [comment]
:lgtm:

---

Reviewed 4 of 11 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[rainsd/server.conf, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-Kf7HIJtKef7F6zDL5V2:-KfCXEJpBz1NlUZ3JPy4:bblc1ub) ([raw file](https://github.com/netsec-ethz/rains/blob/104b405e216b768394b6e97c7f59c59783b6f210/rainsd/server.conf#L1)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

I think we shouldn't have cert+key in the repository: someone will check out the codebase and use those files in production, either by accident or due to incompetence. We could include a small script that generates a self-signed cert+key for testing purposes and then `.gitignore` those locations.
</blockquote></details>

+1 to tobias -- the right way to do this is have the snakeoil cert/key be dynamic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-:-KfCXb_p2JkKXE_n8R1C:bnfp4nl)*

**Comment by fehlmach** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[rainsd/switchboard.go, line 214 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-KfC1Ahe24YvTI-vsVeu:-KfFu7eWeiBz6Yx8dmdV:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/e49c147efe5b1f3820f53934d900e5a1e86bca91/rainsd/switchboard.go#L214)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Hard code them for now. We can later decide which ones have no default and must always be user-supplied.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2)*

**Comment by klausman** [comment]
Reviewed 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2)*

**Comment by britram** [comment]
:lgtm:

---

Reviewed 1 of 11 files at r2, 1 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/2#-:-KfHGyGwnmKZyL2WbOps:bnfp4nl)*

**Pull request merged**
