### PR TITLE
Update SCION Dispatcher-less

### PR DESCRIPTION
**Pull request by juagargi**
The new scionproto codebase upstream uses a thin dispatcher (dispatcher-less mode).
Adapt RAINS to it.
Adapt CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/243)

### CODE REVIEW

**Comment by martenwallewein** [comment]
Looks good to me! Again, thanks Juan for tackling this! 

I have one question out of curiosity: what is the intention behind the go version 1.21.10 and the toolchain 1.21.11, is it intended that these differ by one patch version?

**Comment by juagargi** [comment]
Those came directly by using `go get scionproto-new` and `go mod tidy`. I have not worried too much about them though.
If you find out what they do and why they ended up there, please let us know :smiley: 
In scionproto's `go.mod` they only declare the version of go
```
go 1.21.10
```
But no mention to the toolchain.
BTW, the last version of go 1.21 is 1.21.11. That might be the reason of the toolchain version being one higher up than th go one? Idk.

**Review by martenwallewein — APPROVED** [review]
Understood the point with the go toolchain version. Don't think that it affects this PR, can be updated later anyway.

In summary everything looks good to me.

**Review by martenwallewein — COMMENTED** [review]
:lgtm: 

> Reviewed 72 of 72 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/243#-:-O-kqmv70bZwfgcGouA9:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
