### PR TITLE
Validity of sections

### PR DESCRIPTION
**Pull request by fehlmach**
The validity period of a section is now also determined by the validity of the public key which is used to verify the contained signature. 
section is also valid in gaps in validity life times when an assertion contains multiple signatures only the earliest and latest points in time are taken into account for caching

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/28)

### CODE REVIEW

**Comment by britram** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[rainslib/datamodel.go, line 173 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmBG8Zvp_SCrG01nMwn:-KmBG8Zw5qJGtv2h7ZIi:bkekxrq) ([raw file](https://github.com/netsec-ethz/rains/blob/b544e6fae2271e6b0c345c1ed328c3d5bed70de4/rainslib/datamodel.go#L173)):*
> ```Go
> 	if validSince < a.validSince {
> 		if validSince > time.Now().Add(maxValidity).Unix() {
> 			log.Warn("Assertion validity starts too much in the future. Drop Assertion.", "assertion", *a)
> ```

fyi: nit: s/too much/too far/

---

*[rainslib/datamodel.go, line 181 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmBGFbEc3cpMTJChU6n:-KmBGFbEc3cpMTJChU6o:bk6j0uo) ([raw file](https://github.com/netsec-ethz/rains/blob/b544e6fae2271e6b0c345c1ed328c3d5bed70de4/rainslib/datamodel.go#L181)):*
> ```Go
> 		if validUntil > time.Now().Add(maxValidity).Unix() {
> 			a.validUntil = time.Now().Add(maxValidity).Unix()
> 			log.Warn("Reduced the validity of the assertion in the cache. Validity exceeded upper bound", "assertion", *a)
> ```

fyi: nit: you didn't really reduce the validity; you limited or capped it.

---

*[rainslib/datamodel.go, line 284 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmBGMTchlmE_D4jKx3n:-KmBGMTdYDnoP_OLyPeH:bjalohx) ([raw file](https://github.com/netsec-ethz/rains/blob/b544e6fae2271e6b0c345c1ed328c3d5bed70de4/rainslib/datamodel.go#L284)):*
> ```Go
> 	if validSince < s.validSince {
> 		if validSince > time.Now().Add(maxValidity).Unix() {
> 			log.Warn("Shard validity starts too much in the future. Drop Shard.", "shard", *s)
> ```

fyi nit as above

---

*[rainslib/datamodel.go, line 292 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmBGPWvkclmcR3ExWDp:-KmBGPWwsXpBW0780B77:bjalohx) ([raw file](https://github.com/netsec-ethz/rains/blob/b544e6fae2271e6b0c345c1ed328c3d5bed70de4/rainslib/datamodel.go#L292)):*
> ```Go
> 		if validUntil > time.Now().Add(maxValidity).Unix() {
> 			s.validUntil = time.Now().Add(maxValidity).Unix()
> 			log.Warn("Reduced the validity of the shard in the cache. Validity exceeded upper bound", "shard", *s)
> ```

fyi nit as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-:-KmBGXURG2jbh4q5alh-:bnfp4nl)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[rainslib/datamodel.go, line 173 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmBG8Zvp_SCrG01nMwn:-KmC-PsWlD-PZvkrdf4a:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/b544e6fae2271e6b0c345c1ed328c3d5bed70de4/rainslib/datamodel.go#L173)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

fyi: nit: s/too much/too far/
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 181 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmBGFbEc3cpMTJChU6n:-KmC-PaPqjwBE-Tb4RNN:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/b544e6fae2271e6b0c345c1ed328c3d5bed70de4/rainslib/datamodel.go#L181)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

fyi: nit: you didn't really reduce the validity; you limited or capped it.
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 284 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmBGMTchlmE_D4jKx3n:-KmC-PGe3bNdMMxN4Rm4:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/b544e6fae2271e6b0c345c1ed328c3d5bed70de4/rainslib/datamodel.go#L284)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

fyi nit as above
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 292 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmBGPWvkclmcR3ExWDp:-KmC-P316U7D1LmYx6E5:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/b544e6fae2271e6b0c345c1ed328c3d5bed70de4/rainslib/datamodel.go#L292)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

fyi nit as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/28)*

**Comment by klausman** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[rainsd/verify.go, line 414 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRPWu5Sz_HZgjPiC2b:-KmRPWu5Sz_HZgjPiC2c:b-xhi4m0) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainsd/verify.go#L414)):*
> ```Go
> 		maxValidity = Config.MaxCacheZoneValidity
> 	default:
> 		log.Warn("Not supported section")
> ```

Log the type here.

---

*[rainslib/datamodel.go, line 173 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRRh31daodoeZWqeUK:-KmRRh31daodoeZWqeUL:bhwhs2z) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L173)):*
> ```Go
> 	if validSince < a.validSince {
> 		if validSince > time.Now().Add(maxValidity).Unix() {
> 			log.Warn("Assertion validity starts too far in the future. Drop Assertion.", "assertion", *a)
> ```

IIUC, this does not log `validSince`, only `a.validSince` (implicitly) but it should log both.

---

*[rainslib/datamodel.go, line 181 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRRyHr4i-g8AhGlAHk:-KmRRyHr4i-g8AhGlAHl:b2nreh6) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L181)):*
> ```Go
> 		if validUntil > time.Now().Add(maxValidity).Unix() {
> 			a.validUntil = time.Now().Add(maxValidity).Unix()
> 			log.Warn("Limit the validity of the assertion in the cache. Validity exceeded upper bound", "assertion", *a)
> ```

Same as above.

---

*[rainslib/datamodel.go, line 219 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRS7MYBSIK00zXDFVU:-KmRS7MYBSIK00zXDFVV:b-887tdj) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L219)):*
> ```Go
> 	RangeTo     string
> 	validSince  int64
> 	validUntil  int64
> ```

Btw, what is the zero point and unit of these two? Would it make sense to make them `uint64`?

---

*[rainslib/datamodel.go, line 284 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRSJ-qVJhAiSCJFH-d:-KmRSJ-qVJhAiSCJFH-e:b-hghg6n) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L284)):*
> ```Go
> 	if validSince < s.validSince {
> 		if validSince > time.Now().Add(maxValidity).Unix() {
> 			log.Warn("Shard validity starts too far in the future. Drop Shard.", "shard", *s)
> ```

Same re: logging `validSince`

---

*[rainslib/datamodel.go, line 292 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRSNGZ-y3WvyL24M5g:-KmRSNGZ-y3WvyL24M5h:bio604c) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L292)):*
> ```Go
> 		if validUntil > time.Now().Add(maxValidity).Unix() {
> 			s.validUntil = time.Now().Add(maxValidity).Unix()
> 			log.Warn("Limit the validity of the shard in the cache. Validity exceeded upper bound", "shard", *s)
> ```

And again.

---

*[rainslib/datamodel.go, line 400 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRSSlIXBy86Ayoym_B:-KmRSSlIXBy86Ayoym_C:b-s8nh3x) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L400)):*
> ```Go
> 	if validSince < z.validSince {
> 		if validSince > time.Now().Add(maxValidity).Unix() {
> 			log.Warn("Zone validity starts too far in the future. Drop Zone.", "zone", *z)
> ```

Log `validSince`

---

*[rainslib/datamodel.go, line 408 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRSVnbtrVVm9A_QOzP:-KmRSVnbtrVVm9A_QOzQ:b-s8nh3x) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L408)):*
> ```Go
> 		if validUntil > time.Now().Add(maxValidity).Unix() {
> 			z.validUntil = time.Now().Add(maxValidity).Unix()
> 			log.Warn("Limit the validity of the zone in the cache. Validity exceeded upper bound", "zone", *z)
> ```

Log `validSince`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/28)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[rainsd/verify.go, line 414 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRPWu5Sz_HZgjPiC2b:-KmRTqL7BdAWu7YCAvfT:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainsd/verify.go#L414)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Log the type here.
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 173 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRRh31daodoeZWqeUK:-KmRUjxJfgqYxwxrzQe1:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L173)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

IIUC, this does not log `validSince`, only `a.validSince` (implicitly) but it should log both.
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 181 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRRyHr4i-g8AhGlAHk:-KmRUkH2FjL3ljJ07CoC:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L181)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 219 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRS7MYBSIK00zXDFVU:-KmRUzsvJOgAyx3mua85:b-o2qci7) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L219)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Btw, what is the zero point and unit of these two? Would it make sense to make them `uint64`?
</blockquote></details>

seconds since January 1970 by using this function of the time package https://golang.org/src/time/time.go?s=24162:24188#L833
uint64 would also work but then we have to add a lot of conversations everywhere. So I would leave it that way, but I added a comment to the variable 

---

*[rainslib/datamodel.go, line 284 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRSJ-qVJhAiSCJFH-d:-KmRUlQYw6kNUg1MdA9V:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L284)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Same re: logging `validSince`
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 292 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRSNGZ-y3WvyL24M5g:-KmRUlfPSqA_eTw2HHP8:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L292)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

And again.
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 400 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRSSlIXBy86Ayoym_B:-KmRUm82bGQ_V-PIbzpN:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L400)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Log `validSince`
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 408 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/28#-KmRSVnbtrVVm9A_QOzP:-KmRUmNwNpqeJgZoialn:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/04accf4615949405b8c7ca58997b5af092cf135a/rainslib/datamodel.go#L408)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Log `validSince`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/28)*

**Comment by klausman** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/28)*

**Pull request merged**
