### PR TITLE
improved logging of zone file parser, added line number

### PR DESCRIPTION
**Pull request by fehlmach**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/27)

### CODE REVIEW

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[utils/zoneFileParser/zoneFileParser.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/27#-KlwweTRBMr7RgHYRFEA:-KlwweTRBMr7RgHYRFEB:bk1spti) ([raw file](https://github.com/netsec-ethz/rains/blob/a8ecac6ceddb71bae4a1b61377941b641e06656b/utils/zoneFileParser/zoneFileParser.go#L26)):*
> ```Go
> 	assertions := []*rainslib.AssertionSection{}
> 	scanner := NewWordScanner(zoneFile)
> 	lineNrLogger = log.New("lineNr", log.Lazy{scanner.LineNumber})
> ```

Does this include the filename being read?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/27#-:-Klwx-XRofa5azHaB5x7:bnfp4nl)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[utils/zoneFileParser/zoneFileParser.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/27#-KlwweTRBMr7RgHYRFEA:-Klx1whbkKBHeoKo1gH7:b-k3o7c4) ([raw file](https://github.com/netsec-ethz/rains/blob/a8ecac6ceddb71bae4a1b61377941b641e06656b/utils/zoneFileParser/zoneFileParser.go#L26)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Does this include the filename being read?
</blockquote></details>

no it does not. The function ParseZoneFile takes the already read zone file. Should I add the filePath as a parameter to the function such that i can log it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/27)*

**Comment by klausman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[utils/zoneFileParser/zoneFileParser.go, line 26 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/27#-KlwweTRBMr7RgHYRFEA:-KlxFplURWIEZsCNihCT:bjvggnq) ([raw file](https://github.com/netsec-ethz/rains/blob/a8ecac6ceddb71bae4a1b61377941b641e06656b/utils/zoneFileParser/zoneFileParser.go#L26)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

no it does not. The function ParseZoneFile takes the already read zone file. Should I add the filePath as a parameter to the function such that i can log it?
</blockquote></details>

That would be nice, yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/27)*

**Comment by britram** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/27#-:-KlxMIm0l0PpLFrqanqY:bnfp4nl)*

**Pull request merged**
