### PR TITLE
Concurrency safe set data structure

### PR DESCRIPTION
**Pull request by fehlmach**
Concurrency safe set data structure, refactoring go routine calls

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/7)

### CODE REVIEW

**Comment by klausman** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[rainsdig/rainsdig.go, line 87 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/7#-KgUEZaYYE_pLmZfIsQi:-KgUEZaZl0BflyjKxrd9:b-vkpuek) ([raw file](https://github.com/netsec-ethz/rains/blob/ae2a958f7ca8de53f554be1e0e495e6925cb2373/rainsdig/rainsdig.go#L87)):*
> ```Go
> func sendQuery(query []byte, ipAddress string, port uint) error {
> 	conf := &tls.Config{
> 		InsecureSkipVerify: true,
> ```

FYI This probably should become a command-line toggle at some point.

---

*[rainslib/rainslibUtil.go, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/7#-KgUEqGvi_OlduzctoX3:-KgUEqGvi_OlduzctoX4:b-nycq3u) ([raw file](https://github.com/netsec-ethz/rains/blob/ae2a958f7ca8de53f554be1e0e495e6925cb2373/rainslib/rainslibUtil.go#L14)):*
> ```Go
> 	_, err := rand.Read(token[:])
> 	if err != nil {
> 		log.Warn("Error during random token generation")
> ```

Log the error here.

---

*[utils/set/set.go, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/7#-KgUF6f5quZ9mFuukxf3:-KgUF6f5quZ9mFuukxf4:b-svlj2o) ([raw file](https://github.com/netsec-ethz/rains/blob/ae2a958f7ca8de53f554be1e0e495e6925cb2373/utils/set/set.go#L32)):*
> ```Go
> 
> //Delete removes item from the hash set if it is contained. This method is concurrency safe.
> func (set *Set) Delete(item interface{}) {
> ```

I think it would be useful to have `Delete` return whether the element was in the set. That way, it can be used with similar semantics as Python's `discard()`and `remove()` operations on sets.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/7)*

**Comment by fehlmach** [comment]
Review status: 7 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[rainsdig/rainsdig.go, line 87 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/7#-KgUEZaYYE_pLmZfIsQi:-KgmmhnQ6pd5QMiVGUZC:b9ofby7) ([raw file](https://github.com/netsec-ethz/rains/blob/ae2a958f7ca8de53f554be1e0e495e6925cb2373/rainsdig/rainsdig.go#L87)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

FYI This probably should become a command-line toggle at some point.
</blockquote></details>

Done. added todo

---

*[rainslib/rainslibUtil.go, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/7#-KgUEqGvi_OlduzctoX3:-KgmmsXBwUEaSlea0eY0:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/ae2a958f7ca8de53f554be1e0e495e6925cb2373/rainslib/rainslibUtil.go#L14)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Log the error here.
</blockquote></details>

Done.

---

*[utils/set/set.go, line 32 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/7#-KgUF6f5quZ9mFuukxf3:-Kgmmy9SewIA6vA2nmoE:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/ae2a958f7ca8de53f554be1e0e495e6925cb2373/utils/set/set.go#L32)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

I think it would be useful to have `Delete` return whether the element was in the set. That way, it can be used with similar semantics as Python's `discard()`and `remove()` operations on sets.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/7)*

**Comment by klausman** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[utils/cache/cache.go, line 130 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/7#-KgtCtbOloJrltFFEDmu:-KgtCtbOloJrltFFEDmv:b-2ech4q) ([raw file](https://github.com/netsec-ethz/rains/blob/3d2a10146efb23daa0e701a093b4ca938fde9682/utils/cache/cache.go#L130)):*
> ```Go
> 	var element *list.Element
> 	if internal {
> 		element = c.list.PushFront(&entry{internal: true, context: context, key: key, value: value})
> ```

Minor (so feel free to ignore):
The creation of the `entry` literal could be done before `if internal {`, using `x:=entry{internal: internal, ...}` and then using `x` in both `PushFront` calls. Thus making the difference in calls (`c.lruList` vs. `c.List`) slightly more obvious (it also makes changes to the `entry` struct easier to get right). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/7)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[utils/cache/cache.go, line 130 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/7#-KgtCtbOloJrltFFEDmu:-KgxFHWauDeV9QU5hoph:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/3d2a10146efb23daa0e701a093b4ca938fde9682/utils/cache/cache.go#L130)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Minor (so feel free to ignore):
The creation of the `entry` literal could be done before `if internal {`, using `x:=entry{internal: internal, ...}` and then using `x` in both `PushFront` calls. Thus making the difference in calls (`c.lruList` vs. `c.List`) slightly more obvious (it also makes changes to the `entry` struct easier to get right). 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/7)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/7#-:-KgxFiogsRbuSw3Uyw1k:bnfp4nl)*

**Pull request merged**
