### PR TITLE
Reverse Lookup

### PR DESCRIPTION
**Pull request by fehlmach**
reverse lookup implemented.
Trie datastructure implemented for fast reverse lookup.
Not yet tested as the signing format changed and the signatures are not valid anymore. This issue will be addressed in the next PR.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/32)

### CODE REVIEW

**Comment by klausman** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[rainsd/engine.go, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVNbgC_3eq3ZmuS0Ki:-KmVNbgC_3eq3ZmuS0Kj:b6syxaf) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/rainsd/engine.go#L99)):*
> ```Go
> 		}
> 	case *rainslib.AddressAssertionSection:
> 		log.Info("Start processing address assertion", "assertion", section)
> ```

This should probably be `log.Debug`

---

*[utils/binaryTrie/binaryTrie.go, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVPShCOK7A21hXFFKI:-KmVPShCOK7A21hXFFKJ:b-mtc9ke) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/utils/binaryTrie/binaryTrie.go#L15)):*
> ```Go
> 
> //Trie is a node of a binary trie.
> type Trie struct {
> ```

Shouldn't it be called `Node`, then?

---

*[utils/binaryTrie/binaryTrie.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVQ0rRBJP5m7LCiE_u:-KmVQ0rRBJP5m7LCiE_v:b2nr4ve) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/utils/binaryTrie/binaryTrie.go#L31)):*
> ```Go
> 
> func get(t *Trie, netAddr *net.IPNet, types []rainslib.ObjectType, depth int) (*rainslib.AddressAssertionSection, *rainslib.AddressZoneSection, bool) {
> 	addrmasks := [8]byte{0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01}
> ```

This seems very IPv4-specific, or am I missing something? If so, what is the story for v6 addresses?

---

*[utils/protoParser/protoParser_test.go, line 55 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVQEYur5LOKt5JrJNI:-KmVQEYur5LOKt5JrJNJ:bi4rqr) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/utils/protoParser/protoParser_test.go#L55)):*
> ```Go
> 		Data:       []byte("SignatureData")}
> 
> 	_, subjectAddress1, _ := net.ParseCIDR("127.0.0.1/32")
> ```

Once supported, we should also have tests with v6 addresses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/32)*

**Comment by britram** [comment]
Reviewed 11 of 15 files at r1, 4 of 9 files at r2.
Review status: 15 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[utils/binaryTrie/binaryTrie.go, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVPShCOK7A21hXFFKI:-KmVTvVhkJ0edbe4UQzw:b-6ddbby) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/utils/binaryTrie/binaryTrie.go#L15)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Shouldn't it be called `Node`, then?
</blockquote></details>

Well, every node of a trie is also a trie...

---

*[utils/binaryTrie/binaryTrie_test.go, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVweXqu1v8ujFgIX31:-KmVweXqu1v8ujFgIX32:b-xroact) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/utils/binaryTrie/binaryTrie_test.go#L35)):*
> ```Go
> 		Data:       []byte("SignatureData")}
> 
> 	_, subjectAddress1, _ := net.ParseCIDR("127.0.0.1/32")
> ```

We need IPv6 test cases here too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/32)*

**Comment by klausman** [comment]
Reviewed 5 of 9 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/32)*

**Comment by klausman** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/32)*

**Comment by fehlmach** [comment]
Review status: 18 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[rainsd/engine.go, line 99 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVNbgC_3eq3ZmuS0Ki:-KmWKFMNEyW9YfAg4noV:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/rainsd/engine.go#L99)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This should probably be `log.Debug`
</blockquote></details>

Done.

---

*[utils/binaryTrie/binaryTrie.go, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVQ0rRBJP5m7LCiE_u:-KmWM8Bg06Md5rWnyPva:bmhwe7z) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/utils/binaryTrie/binaryTrie.go#L31)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This seems very IPv4-specific, or am I missing something? If so, what is the story for v6 addresses?
</blockquote></details>

It works for both. The addrmask is used to get each bit of a byte from left to right.
I pick one byte after the other so in ip6 it just takes longer.

---

*[utils/binaryTrie/binaryTrie_test.go, line 35 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVweXqu1v8ujFgIX31:-KmWM8jd1u8LKW4YDlb2:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/utils/binaryTrie/binaryTrie_test.go#L35)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

We need IPv6 test cases here too
</blockquote></details>

Done.

---

*[utils/protoParser/protoParser_test.go, line 55 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-KmVQEYur5LOKt5JrJNI:-KmWM0UhIPtH2h_aZ0BZ:b72c03z) ([raw file](https://github.com/netsec-ethz/rains/blob/5884955d24743be3701aac7fd658bdc0b7e852ba/utils/protoParser/protoParser_test.go#L55)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Once supported, we should also have tests with v6 addresses.
</blockquote></details>

the parser already supports v6. I added a test case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/32)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-:-KmWU6nhDb6Wh2nsk8X-:bnfp4nl)*

**Comment by britram** [comment]
:lgtm:

---

Reviewed 3 of 9 files at r2, 4 of 4 files at r3, 4 of 4 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/32#-:-KmWVHC9JzoX-acMPm6u:bnfp4nl)*

**Pull request merged**
