### PR TITLE
ZoneFileParser, new signing format, bug fixing, ipv6 tree added

### PR DESCRIPTION
**Pull request by fehlmach**
Basic process is working with the new signing format

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/35)

### CODE REVIEW

**Comment by britram** [comment]
:lgtm:

---

Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[utils/zoneFileParser/signatureEncoder.go, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnJ3XUHL_TXff9HrTrS:-KnJ3XUIBYEXRqLwaEnT:b-xnhaw) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/utils/zoneFileParser/signatureEncoder.go#L15)):*
> ```Go
> 
> //encodeMessage transforms a rains message into a signable format
> func encodeMessage(m *rainslib.RainsMessage) string {
> ```

FYI since Go strings are immutbale, I'm guessint that profiling this will show it to be pretty slow for messages with many large sections, but I'm also guessing most messages in RAINS will have only a small number of sections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-:-KnJ4JqIIhYXwdBks4xM:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[rainsd/serverInfo.go, line 28 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnmtESC60mdSvnNwL7A:-KnmtESC60mdSvnNwL7B:b-wdunr) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/rainsd/serverInfo.go#L28)):*
> ```Go
> 	ServerAddress      rainslib.ConnInfo
> 	MaxConnections     uint
> 	KeepAlivePeriod    time.Duration //in seconds
> ```

This comment does not make sense since `time.Duration` tracks units. It just defaults to seconds. 

---

*[rainsd/serverInfo.go, line 61 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnmtqZw5ljGPhlq9KqM:-KnmtqZw5ljGPhlq9KqN:b-2sam1l) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/rainsd/serverInfo.go#L61)):*
> ```Go
> 	ContextAuthority           []string
> 	ZoneAuthority              []string
> 	MaxCacheValidity           rainslib.MaxCacheValidity //in hours
> ```

This struct is cleare made of `time.Duration`s and thus adding a unit here is meaningless

---

*[rainsd/serverUtil.go, line 75 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnmuMvK-nAtXSa5xlKp:-KnmuMvK-nAtXSa5xlKq:btjz9lr) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/rainsd/serverUtil.go#L75)):*
> ```Go
> 	Config.MaxCacheValidity.AssertionValidity *= time.Hour
> 	Config.MaxCacheValidity.ShardValidity *= time.Hour
> 	Config.MaxCacheValidity.ZoneValidity *= time.Hour
> ```

This makes the Config structure non-idempotent: it would read for example:

```json
"MaxCacheValidity": {
    "AddressAssertionValidity": 1
}
```

But after the code block above, it would marshal as:

```json
"MaxCacheValidity": {
    "AddressAssertionValidity": 60
}
```
since `time.Duration` defaults to outputting seconds.

I am not sure marshalling an existing config object would ever happen, but the unmarshal into the same object still rubs me the wrong. It would probably be better to either have separate Config structures for "this was JSON" and "this is used by the Go code" as we do in the Border Router --- or we rename the hour-based validities in the Config into `AddressAssertionValidityHours` and have a seconds-unit member that is never marshalled (using struct annotations) that is a `time.Duration` and used by the Go code. Then the above code would transform into:

```Go
Config.MaxCacheValidity.AddressAssertionValidity = time.Hour*Config.MaxCacheValidity.AddressAssertionValidityHours
```

I know this would be a lot of work. Another alternative is to make unmarshal functions for these configuration items and use `time.ParseDuration` in them. Then the JSON side would have entries like `1h` for the hourly stuff. The second-based entries would need a trailing `s` to be valid (`time.Duration("1")` returns an error. In essence, the distinction between the two types of duration would go away and the units would always be explicit on the JSON side.

---

*[rainsSiglib/rainsSiglib_test.go, line 39 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnmzDXRvIknhfosAOyK:-KnmzDXRvIknhfosAOyL:b-1g0lnd) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/rainsSiglib/rainsSiglib_test.go#L39)):*
> ```Go
> 
> 	nameObject := rainslib.Object{Type: rainslib.OTName, Value: nameObjectContent}
> 	ip6Object := rainslib.Object{Type: rainslib.OTIP6Addr, Value: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"}
> ```

Unless this actually makes external lookups, you should use the v4 networks from rfc5737 (`192.0.2.0/24`, `198.51.100.0/24`,
   and `203.0.113.0/24`) and `example.com` for domains.

---

*[server/config/rainspub.conf, line 13 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-Knn-5VQL4uDPx4vuRdE:-Knn-5VQL4uDPx4vuRdF:b8tzy9e) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/server/config/rainspub.conf#L13)):*
> ```
> "ZonePublicKeyPath": "keys/zonePublic.key",
> "RootPrivateKeyPath": "keys/rootPrivate.key"
> }
> ```

Add CR at EOF.

---

*[server/config/server.conf, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-Knn-87EwKu1FJtbwLeT:-Knn-87EwKu1FJtbwLeU:ba44fi7) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/server/config/server.conf#L1)):*
> ```
> {
> ```

Normalize this for tabs vs. spaces for indentation.

---

*[utils/zoneFileParser/signatureEncoder.go, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnJ3XUHL_TXff9HrTrS:-Knn-cLc561NJ1Jqva77:b-lcmixx) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/utils/zoneFileParser/signatureEncoder.go#L15)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

FYI since Go strings are immutbale, I'm guessint that profiling this will show it to be pretty slow for messages with many large sections, but I'm also guessing most messages in RAINS will have only a small number of sections.
</blockquote></details>

The typical approach is the same as in Python: make a ~~list~~ slice+append to it, then `Join()` it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/35)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[rainsd/serverInfo.go, line 28 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnmtESC60mdSvnNwL7A:-Ko6FTQy308tY47H10Hm:b2tdv3y) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/rainsd/serverInfo.go#L28)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This comment does not make sense since `time.Duration` tracks units. It just defaults to seconds. 
</blockquote></details>

see comment below

---

*[rainsd/serverInfo.go, line 61 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnmtqZw5ljGPhlq9KqM:-Ko6FVtTsJtsWF7aJymk:b2tdv3y) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/rainsd/serverInfo.go#L61)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This struct is cleare made of `time.Duration`s and thus adding a unit here is meaningless
</blockquote></details>

see comment below

---

*[rainsd/serverUtil.go, line 75 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnmuMvK-nAtXSa5xlKp:-Ko6F8HBFRcaJztApjt5:bma1iy8) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/rainsd/serverUtil.go#L75)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This makes the Config structure non-idempotent: it would read for example:

```json
"MaxCacheValidity": {
    "AddressAssertionValidity": 1
}
```

But after the code block above, it would marshal as:

```json
"MaxCacheValidity": {
    "AddressAssertionValidity": 60
}
```
since `time.Duration` defaults to outputting seconds.

I am not sure marshalling an existing config object would ever happen, but the unmarshal into the same object still rubs me the wrong. It would probably be better to either have separate Config structures for "this was JSON" and "this is used by the Go code" as we do in the Border Router --- or we rename the hour-based validities in the Config into `AddressAssertionValidityHours` and have a seconds-unit member that is never marshalled (using struct annotations) that is a `time.Duration` and used by the Go code. Then the above code would transform into:

```Go
Config.MaxCacheValidity.AddressAssertionValidity = time.Hour*Config.MaxCacheValidity.AddressAssertionValidityHours
```

I know this would be a lot of work. Another alternative is to make unmarshal functions for these configuration items and use `time.ParseDuration` in them. Then the JSON side would have entries like `1h` for the hourly stuff. The second-based entries would need a trailing `s` to be valid (`time.Duration("1")` returns an error. In essence, the distinction between the two types of duration would go away and the units would always be explicit on the JSON side.



</blockquote></details>

Yes that makes sense. The way it is now is not a nice solution. But in my opinion this is not a priority right now, so I file an issue to fix this.

---

*[rainsSiglib/rainsSiglib_test.go, line 39 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnmzDXRvIknhfosAOyK:-Ko6GAFPTFRfBGBbOmFs:b6ii8qv) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/rainsSiglib/rainsSiglib_test.go#L39)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Unless this actually makes external lookups, you should use the v4 networks from rfc5737 (`192.0.2.0/24`, `198.51.100.0/24`,
   and `203.0.113.0/24`) and `example.com` for domains.
</blockquote></details>

ok i did not know that. Thank you for the suggestion.

---

*[server/config/rainspub.conf, line 13 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-Knn-5VQL4uDPx4vuRdE:-Ko6IeDkwJDot0W2rUQB:bb7f2mf) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/server/config/rainspub.conf#L13)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Add CR at EOF.
</blockquote></details>

done

---

*[server/config/server.conf, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-Knn-87EwKu1FJtbwLeT:-Ko6JJY2gRwXzzA8zWxK:b-b53dpx) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/server/config/server.conf#L1)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Normalize this for tabs vs. spaces for indentation.
</blockquote></details>

I use only spaces and deleted the trailing spaces. Have a look in the next pr at the two config files in serverCH

---

*[utils/zoneFileParser/signatureEncoder.go, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KnJ3XUHL_TXff9HrTrS:-Ko6JceJvcpcJPQQUVA0:bb7f2mf) ([raw file](https://github.com/netsec-ethz/rains/blob/1ddb20ecefc1852a0635cf0834df4363e5de757f/utils/zoneFileParser/signatureEncoder.go#L15)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

The typical approach is the same as in Python: make a ~~list~~ slice+append to it, then `Join()` it.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/35)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-:-Ko7jDfHOFlbPyq4IwJu:bnfp4nl)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: 37 of 40 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-:-KoCA4PDNuOF-VRdHgRc:bnfp4nl)*

**Comment by klausman** [comment]
Reviewed 1 of 3 files at r2.
Review status: 38 of 40 files reviewed at latest revision, 1 unresolved discussion.

---

*[serverCH/serverCH, line 0 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-KoCANE5poGUGPNnZJYO:-KoCANE5poGUGPNnZJYP:bum27ir) ([raw file](https://github.com/netsec-ethz/rains/blob/b135e492b5b59083b0c553461824b423a3571165/serverCH/serverCH#L0)):*
What is the purpose of this file (and `serverRoot/serverRoot` below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/35)*

**Comment by klausman** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/35)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/35#-:-KoCBdvRIz8dwCkPPBqM:bnfp4nl)*

**Pull request merged**
