### PR TITLE
implementation inbox.go, notification.go, parser, update datamodel

### PR DESCRIPTION
**Pull request by fehlmach**
implementation inbox.go, notification.go, parser, update datamodel

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/5)

### CODE REVIEW

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[rainsd/engine.go, line 12 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kffk0wipMvAA7C3wA9t:-Kffv4sNaMnk9ZSg51xl:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/engine.go#L12)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

pendin*g*, I suspect?
</blockquote></details>

Done.

---

*[rainsd/engine.go, line 36 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-KffkFyCCs54fHNG5WeY:-KfftFRHBFUcZVgv8Fo3:b-hyls55) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/engine.go#L36)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

The names of these three functions do not really work for me. But we can always rename them later (once I have an idea what they *should* be...)
</blockquote></details>

Yes, totally agree.

---

*[rainsd/engine.go, line 41 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-KffkfdUSg_xDnRyjSLG:-KfftnC1x-_dUv_JZQjW:b-7xgqfu) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/engine.go#L41)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This should probably return whether it only placed something in the query pipeline or if the query was returned from the cache (a bit like POSIX's EAGAIN)
</blockquote></details>

We could do that but the calling function does not care about it, because it hands it off and will not process it further.

---

*[rainsd/inbox.go, line 80 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-KffobyQekOBr2rly1pi:-Kffv0FVWdOqx4JLxsk-:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/inbox.go#L80)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

`cap` is a Go builtin: https://golang.org/pkg/builtin/#cap so please replace it woth something else (`caps`? there's likely more than one in there, anyway).
</blockquote></details>

Done.

---

*[rainsd/inbox.go, line 89 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-KffqC7Mh_vNVEXz-Vp6:-KffvLgsZ2eQvAmDVri_:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/inbox.go#L89)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This should log what the received caps look like (as a hexdump or somesuch)
</blockquote></details>

Done.

---

*[rainsd/inbox.go, line 125 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kffr7Kwci7uHLhnfpck:-KffwluG3GKR8vTvmU9_:biveohl) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/inbox.go#L125)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

What happens here if `len(tok)>32`?
</blockquote></details>

I guess it panics. This cannot happen because the parser returns en error if the token is larger than 32 but I should add a remark to the comment about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/5)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[rainsd/inbox.go, line 117 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kffqjl0451W7pxKd8pS:-KffymaaJ5E2pXCXObzB:b-4b0l0f) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/inbox.go#L117)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

This should return `err` in this case and above and `nil` if everything went fine.
</blockquote></details>

In case of an error we just stop processing this query and drop it. Thus it makes in this case no sense to pass the error along as it only complicates reading the code. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/5)*

**Comment by britram** [comment]
Reviewed 7 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[rainsd/engine.go, line 36 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-KffkFyCCs54fHNG5WeY:-Kg-7I5DK2i4sIYi4TfS:b-cdfgdw) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/engine.go#L36)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

Yes, totally agree.
</blockquote></details>

OK -- note there will be some other refactoring happening in the engine soon ("Body" -> "Section"); we can do a full rename pass once things work.

---

*[rainsd/inbox.go, line 117 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kffqjl0451W7pxKd8pS:-Kg-8Oi-2LT7PfU3OfgW:b-pin33a) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/inbox.go#L117)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

In case of an error we just stop processing this query and drop it. Thus it makes in this case no sense to pass the error along as it only complicates reading the code. 
</blockquote></details>

this seems to me like it should be logged, though...

---

*[rainsd/inbox.go, line 125 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kffr7Kwci7uHLhnfpck:-Kg-8befDOVXXXXb2408:bt3sv0x) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/inbox.go#L125)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

I guess it panics. This cannot happen because the parser returns en error if the token is larger than 32 but I should add a remark to the comment about that.
</blockquote></details>

alternately, you could take the max of len(tok) and 32; this makes it clear what the intention is, and can't panic.

there's a philosophical discussion that we could have here about checking invariants in private functions. adding a comment is probably sufficient for now.

---

*[rainsd/inbox.go, line 136 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-9cvvopdoJnPXkXoo:-Kg-9cvw-DwkZqqBg9GQ:b-x8rv6e) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/inbox.go#L136)):*
> ```Go
> 
> //addNotifToQueue adds a rains message containing one notification message body to the queue if the token is present in the activeToken cache
> func addNotifToQueue(msg rainslib.RainsMessage, sender ConnInfo) {
> ```

+1 to "let's consider renaming things" here, too...

---

*[rainsd/inbox.go, line 166 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-9pHEsxH-8MtLOZr1:-Kg-9pHFFeXfkq40EPUH:b97co0z) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/inbox.go#L166)):*
> ```Go
> func workBoth() {
> 	for {
> 	innerLoop:
> ```

FYI: the code as written here will process *all* priority messages before processing *any* normal messages. Is this the intention?

---

*[rainsd/notification.go, line 12 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-BGPwjHhNUBztqHvZ:-Kg-BGPxy7iEHsVbaHrQ:bpw0lgd) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/notification.go#L12)):*
> ```Go
> func Notify(msg rainslib.RainsMessage, sender ConnInfo) {
> 	body := msg.Content[0].(rainslib.NotificationBody)
> 	notifLog := log.New("NotificationMsgBody", body)
> ```

FYI: not sure this is the right logging scope to use here, but as long as it's unique we can do this as part of the rename pass.

---

*[rainsd/serverUtil.go, line 2 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-DDgJfdKUSOZKTojW:-Kg-DDgJfdKUSOZKTojX:bb3cfay) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L2)):*
> ```Go
> package rainsd
> ```

FYI I'm still not sure all of this stuff belongs in one file. We should probably be looking for things to evict out into their own files (e.g. Cache seems like a candidate) with more transparent names than serverUtil.

---

*[rainsd/serverUtil.go, line 11 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-Bc3kWM0NTgewmzJ_:-Kg-Bc3lweWa1AQP37pw:b-xanjm5) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L11)):*
> ```Go
> 	"time"
> 
> 	lru "github.com/hashicorp/golang-lru"
> ```

BTW what a terrible package name, shame on hashicorp.

---

*[rainsd/serverUtil.go, line 45 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-BlPMUV_MJjqsobX4:-Kg-BlPMUV_MJjqsobX5:b-7yv8fg) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L45)):*
> ```Go
> 
> 	//engine
> 	AssertionCacheSize    uint
> ```

FYI per our discussion today, this should be the number of things that aren't "permanently" in the cache.

---

*[rainsd/serverUtil.go, line 85 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-CmpJ3X6F9fZabn3l:-Kg-CmpKg-xy9v4UUJ8J:bbjzreb) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L85)):*
> ```Go
> 
> const (
> 	NoCapability Capability = "none"
> ```

why isn't this an empty string? "none" is not a valid URI, but this seems like a needless magic value.

---

*[rainsd/serverUtil.go, line 116 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-E6DVsahmS_a1Zo4j:-Kg-E6DVsahmS_a1Zo4k:b-qtn1up) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L116)):*
> ```Go
> 	content := []rainslib.MessageBody{rainslib.NotificationBody{Type: rainslib.MsgTooLarge, Token: token, Data: data}}
> 	msg := rainslib.RainsMessage{Token: GenerateToken(), Content: content}
> 	//TODO CFE do we sign a notification msg?
> ```

Unless the server is configured to with an infrakey pair (which is actually something we should file as an enhancement issue, but probably not tackle on this contract), no. Signing notifications only make sense when running RAINS over a transport with no security (such as raw UDP, not yet specified)...

---

*[rainsd/serverUtil.go, line 120 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-EjhJv5AcL8ljGCZ3:-Kg-EjhKPPXbwu8LPIwU:bt5jwde) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L120)):*
> ```Go
> }
> 
> var counter = 0
> ```

what does this count?

---

*[rainsd/serverUtil.go, line 124 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-EpOmtU8r_gn9PGg2:-Kg-EpOmtU8r_gn9PGg3:bnd6jqf) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L124)):*
> ```Go
> //GenerateTocken generates a new unique Token
> func GenerateToken() rainslib.Token {
> 	//TODO CFE use uuid to create token
> ```

Given the design of the protocol, trivially guessable tokens are bad (note to self this should be in the draft)... UUIDs aren't necessarily hard enough to guess, suggest using a crypto RNG.

---

*[rainsd/serverUtil.go, line 152 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-HOBvIxaOOREOrGuL:-Kg-HOBvIxaOOREOrGuM:b-fc4wcl) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L152)):*
> ```Go
> type LRUCache struct {
> 	Cache *lru.Cache
> }
> ```

You did this so you can add methods to the underlying lru.Cache object, correct?

---

*[rainsd/switchboard_test.go, line 34 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-HgybYs5h4rGS7ep8:-Kg-HgycpbcrSSTyQhI6:bjviik3) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/switchboard_test.go#L34)):*
> ```Go
> 		}
> 	}
> }*/
> ```

I presume the tests come back at some point? While commenting out tests is one way to keep them from failing, but...

---

*[rainslib/datamodel.go, line 156 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-J5pmQJQeOEuMhlxI:-Kg-J5pmQJQeOEuMhlxJ:b-iqmqb4) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainslib/datamodel.go#L156)):*
> ```Go
> 
> const (
> 	DANE KeySpace = iota
> ```

RAINS, not DANE. :)

---

*[rainslib/datamodel.go, line 163 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-JOZ8upvoMI6CYTPg:-Kg-JOZ9gPC-FQ4sZeIo:beoc7xg) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainslib/datamodel.go#L163)):*
> ```Go
> 
> const (
> 	Sha256 CipherType = iota
> ```

these constants should be assigned as in the draft. you can add sha256 for testing as -1.

---

*[utils/parser/rainsMsgParser.go, line 2 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-Jh9FMc6YCvw32WrN:-Kg-Jh9FMc6YCvw32WrO:b-vs2qtk) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/utils/parser/rainsMsgParser.go#L2)):*
> ```Go
> package parser
> ```

OK, tests for this would be nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/5)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[rainsd/engine.go, line 36 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-KffkFyCCs54fHNG5WeY:-Kg-MWoHb1GCYm7PEqRF:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/engine.go#L36)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

OK -- note there will be some other refactoring happening in the engine soon ("Body" -> "Section"); we can do a full rename pass once things work.
</blockquote></details>

Done.

---

*[rainsd/inbox.go, line 117 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kffqjl0451W7pxKd8pS:-Kg-fKuWsx1kQdA_xlp7:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/inbox.go#L117)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

this seems to me like it should be logged, though...
</blockquote></details>

Done.

---

*[rainsd/inbox.go, line 125 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kffr7Kwci7uHLhnfpck:-Kg-fOxOfKXfgkI-tKj5:bp0nop9) ([raw file](https://github.com/netsec-ethz/rains/blob/253f7749ddc051d7202adbe711c7b10f1e948bba/rainsd/inbox.go#L125)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

alternately, you could take the max of len(tok) and 32; this makes it clear what the intention is, and can't panic.

there's a philosophical discussion that we could have here about checking invariants in private functions. adding a comment is probably sufficient for now.
</blockquote></details>

Done. We only handle 16 byte tokens and pad them if they are too short

---

*[rainsd/inbox.go, line 136 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-9cvvopdoJnPXkXoo:-Kg-fgsfSbgcHgpLYZbY:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/inbox.go#L136)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

+1 to "let's consider renaming things" here, too...
</blockquote></details>

Done.

---

*[rainsd/inbox.go, line 166 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-9pHEsxH-8MtLOZr1:-Kg-gWqZtVX1HRQVk996:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/inbox.go#L166)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

FYI: the code as written here will process *all* priority messages before processing *any* normal messages. Is this the intention?
</blockquote></details>

Done.

---

*[rainsd/notification.go, line 12 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-BGPwjHhNUBztqHvZ:-Kg-gg5D37NI__EOFXlk:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/notification.go#L12)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

FYI: not sure this is the right logging scope to use here, but as long as it's unique we can do this as part of the rename pass.
</blockquote></details>

Done.

---

*[rainsd/serverUtil.go, line 85 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-CmpJ3X6F9fZabn3l:-Kg-i-ZFnigbNWeA_Wb9:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L85)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

why isn't this an empty string? "none" is not a valid URI, but this seems like a needless magic value.
</blockquote></details>

Done.

---

*[rainsd/serverUtil.go, line 116 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-E6DVsahmS_a1Zo4j:-Kg-mpiQY1pyHqrFZave:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L116)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

Unless the server is configured to with an infrakey pair (which is actually something we should file as an enhancement issue, but probably not tackle on this contract), no. Signing notifications only make sense when running RAINS over a transport with no security (such as raw UDP, not yet specified)...
</blockquote></details>

Done.

---

*[rainsd/serverUtil.go, line 120 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-EjhJv5AcL8ljGCZ3:-Kg-kW0t-mq5nRKyQUFL:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L120)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

what does this count?
</blockquote></details>

Done.

---

*[rainsd/serverUtil.go, line 124 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-EpOmtU8r_gn9PGg2:-Kg-mdISbjCKadWZJweF:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L124)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

Given the design of the protocol, trivially guessable tokens are bad (note to self this should be in the draft)... UUIDs aren't necessarily hard enough to guess, suggest using a crypto RNG.
</blockquote></details>

Done.

---

*[rainsd/serverUtil.go, line 152 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-HOBvIxaOOREOrGuL:-Kg-jhcqap8LjqQgp3kn:b-4sk6ch) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L152)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

You did this so you can add methods to the underlying lru.Cache object, correct?
</blockquote></details>

Yes and that it implements the Cache interface

---

*[rainsd/switchboard_test.go, line 34 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-HgybYs5h4rGS7ep8:-Kg-jWQRTbSvy4EB2N9_:b-v43mrg) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/switchboard_test.go#L34)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

I presume the tests come back at some point? While commenting out tests is one way to keep them from failing, but...
</blockquote></details>

Yes there will be some tests after its more or less stable. 

---

*[rainslib/datamodel.go, line 156 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-J5pmQJQeOEuMhlxI:-Kg-jT-ay9-XzLu4LI4p:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainslib/datamodel.go#L156)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

RAINS, not DANE. :)
</blockquote></details>

Done.

---

*[rainslib/datamodel.go, line 163 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-JOZ8upvoMI6CYTPg:-Kg-jSJx_JugarNv-NOU:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainslib/datamodel.go#L163)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

these constants should be assigned as in the draft. you can add sha256 for testing as -1.
</blockquote></details>

Done.

---

*[utils/parser/rainsMsgParser.go, line 2 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-Jh9FMc6YCvw32WrN:-Kg-iAmsZe8I1FCOuX9J:b-i64130) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/utils/parser/rainsMsgParser.go#L2)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

OK, tests for this would be nice
</blockquote></details>

Now that we talked about the data structure, I can start writing tests for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/5)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[rainsd/serverUtil.go, line 2 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-DDgJfdKUSOZKTojW:-Kg-nBCEsE72Y8jQ1Rt9:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L2)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

FYI I'm still not sure all of this stuff belongs in one file. We should probably be looking for things to evict out into their own files (e.g. Cache seems like a candidate) with more transparent names than serverUtil.
</blockquote></details>

Done.

---

*[rainsd/serverUtil.go, line 11 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-Bc3kWM0NTgewmzJ_:-Kg-nBZG0bdzlTPScZu4:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L11)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

BTW what a terrible package name, shame on hashicorp.
</blockquote></details>

Done.

---

*[rainsd/serverUtil.go, line 45 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-Kg-BlPMUV_MJjqsobX4:-Kg-nBq9UiAPRrC-OqQs:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/61d6467d041552a31e54a801db7897c2845a294b/rainsd/serverUtil.go#L45)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

FYI per our discussion today, this should be the number of things that aren't "permanently" in the cache.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/5)*

**Comment by britram** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/5)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/5#-:-Kg07wT3Oo2B2K32Mjhu:bnfp4nl)*

**Pull request merged**
