### PR TITLE
Prototype of end-to-end integration testing tool

### PR DESCRIPTION
**Pull request by rayhaanj**
These commits implement the basis for the integration testing tool.

You can try it out by running `make` in the base directory of the repository, then running the `./build/integration` binary. The tool will then create a folder under /tmp/RAINSTemp... with a `bin` folder containing the relevant binaries and a config folder containing the configurations.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/76)

### CODE REVIEW

**Comment by rayhaanj** [comment]
784f532 Adds support for running `rainsPub` for the root zone (and generating the root zone data).

**Comment by rayhaanj** [comment]
7b2f744 Verifies the signatures returned from rainspub in the `.` zone are the public keys of the level 2 servers.

**Comment by rayhaanj** [comment]
5f25b06 and 2c7b4ee complete the integration tests by inserting A records to the L2 TLD servers and verifying their contents. The functionality of the integration tests is now complete and ready for review.

**Comment by britram** [comment]
Reviewed 14 of 21 files at r1, 7 of 8 files at r3, 5 of 6 files at r5.
Review status: 26 of 30 files reviewed at latest revision, all discussions resolved.

---

*[configs/chPub/zoneFiles/chZoneFile.txt, line 3 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LACYp_40vmjXazgdmfK:-LACYp_40vmjXazgdmfL:b-sbkjqg) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/configs/chPub/zoneFiles/chZoneFile.txt#L3)):*
> ```
> :Z: ch . [
>                 :S: [
>                         :A: ch  [ :ip4: 178.209.53.76 ]
> ```

eventually we'll want these to be :deleg: assertions, and to have some second-level domains, but this is fine for now.

---

*[configs/rootPub/zoneFiles/rootZoneFile.txt, line 3 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADRHpV3UxRyuPrfVGw:-LADRHpV3UxRyuPrfVGx:bl6920b) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/configs/rootPub/zoneFiles/rootZoneFile.txt#L3)):*
> ```
> :Z: . .   [
>                 :S: [
>                         :A: ch [ :deleg: ed25519 2245137bcb058f799843bb8c6df31927b547e4951142b99ae97c668b076e9d84 ]
> ```

once we have working redirect to a service, and the server can follow service-info, add :redir: here.

---

*[example/pub/main.go, line 11 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADTrdm62KpIeiI18BW:-LADTrdm62KpIeiI18BX:b-togjly) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/example/pub/main.go#L11)):*
> ```Go
> 
> var (
> 	config = flag.String("config", "", "Path to config file.")
> ```

rainspub should probably also take a zonefile as input on the command-line (or via stdin)

---

*[example/server/main.go, line 15 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADU1Ug5RwyMc-fyDQR:-LADU1Ug5RwyMc-fyDQS:b5x9zl3) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/example/server/main.go#L15)):*
> ```Go
> 
> var (
> 	httpAddr  = flag.String("httpAddr", "[::1]:8080", "Address to listen on for info server")
> ```

"httpAddr" doesn't tell me what the HTTP is for; this is for the information/logging stuff, yes? (Try 'info-server', 'debug-listen', or similar)

---

*[example/server/main.go, line 30 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADUOOm6jzIX0AMGH0I:-LADUOOm6jzIX0AMGH0J:b-9lraya) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/example/server/main.go#L30)):*
> ```Go
> </head>
> <h1>Rainsd</h1>
> <tt>Built at commit {{.Commit}}, branch {{.Branch}} on host {{.Host}}.</tt>
> ```

I presume this will eventually give some more information...

---

*[integration/main.go, line 1 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADZAOL4HotSSvg28iH:-LADZAOL4HotSSvg28iI:b-heaxi5) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/integration/main.go#L1)):*
> ```Go
> package main
> ```

The basic organization of this file is good; I'd like to see if there are things we can pull out of this file for more modular testing later.

---

*[integration/main.go, line 35 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADYDxX-pxrBVa3QIYs:-LADYDxX-pxrBVa3QIYt:b-z8hhl2) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/integration/main.go#L35)):*
> ```Go
> 
> var (
> 	l2TLDs       = flag.String("l2TLDs", "ch,de,com", "Comma separated list of level 2 TLDs")
> ```

These are just called TLDs; what's the l2 for?

---

*[integration/main.go, line 36 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADYLJq8NyVAXHgxEjR:-LADYLJq8NyVAXHgxEjS:bn2rjeu) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/integration/main.go#L36)):*
> ```Go
> var (
> 	l2TLDs       = flag.String("l2TLDs", "ch,de,com", "Comma separated list of level 2 TLDs")
> 	domains      = flag.String("domains", "example,gov,edu", "Comma seperated list of domains to create in l2TLDs.")
> ```

these would be RLDs ("registrant level domains")

---

*[integration/main.go, line 39 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADYSg-C49un2-Y_0nY:-LADYSg-C49un2-Y_0nZ:b-b6302l) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/integration/main.go#L39)):*
> ```Go
> 	validity     = flag.Duration("validity", 30*24*time.Hour, "Validity time for signatures and assertions.")
> 	buildDir     = flag.String("buildDir", "build/", "Path to directory containing RAINS binaries.")
> 	ecdsaCurve   = flag.String("ecdsaCurve", "P521", "Which ECDSA curve to use when generating X509 certificates")
> ```

Why can't we use EdDSA here? (on review, because EdDSA for X.509 hasn't been published yet, perhaps...)

---

*[man/rainsd.md, line 78 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADaV3p4KuRLJWWf8kl:-LADaV3p4KuRLJWWf8km:b18s0wz) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/man/rainsd.md#L78)):*
> ```Markdown
> * `MaxCacheValidity`: a map containing validity entries for the caches in the
>     server,
> * `ReapEngineTimeout`
> ```

...to be continued?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/rains/76)*

**Comment by rayhaanj** [comment]
Review status: 25 of 30 files reviewed at latest revision, 6 unresolved discussions.

---

*[example/pub/main.go, line 11 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADTrdm62KpIeiI18BW:-LAJvY__30vYW5jwjp4k:b9lzg0j) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/example/pub/main.go#L11)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

rainspub should probably also take a zonefile as input on the command-line (or via stdin)
</blockquote></details>

Fixed in b44ea43

---

*[example/server/main.go, line 15 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADU1Ug5RwyMc-fyDQR:-LAJw4nM5hN0yih3NP7K:b-863ma4) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/example/server/main.go#L15)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

"httpAddr" doesn't tell me what the HTTP is for; this is for the information/logging stuff, yes? (Try 'info-server', 'debug-listen', or similar)
</blockquote></details>

Named it debugAddr because it listens on that address and serves debug information.

---

*[example/server/main.go, line 30 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADUOOm6jzIX0AMGH0I:-LAJwD7C2Mu6C1WBwszA:b-u095is) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/example/server/main.go#L30)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

I presume this will eventually give some more information...
</blockquote></details>

Yes the plan is for it to have a list of queries that have been processed. Clicking on one of them would show a trace of every step the request went through to be processed. For example if the query failed because the server does not have authoritative data about that zone, then a trace of the steps which led to that decision could be shown. Right now it's hard to see what happens in such cases because the client simply hangs and gives no further information.

---

*[integration/main.go, line 35 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADYDxX-pxrBVa3QIYs:-LAK1QkMEChftRI_h4z9:bfebsq2) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/integration/main.go#L35)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

These are just called TLDs; what's the l2 for?
</blockquote></details>

Renamed to TLD. The L2 was initially because it was the second level server (one below the root).

---

*[integration/main.go, line 36 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADYLJq8NyVAXHgxEjR:-LAK-jUa9r-jx3V6hmoP:b-886gsx) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/integration/main.go#L36)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

these would be RLDs ("registrant level domains")
</blockquote></details>

Fixed

---

*[integration/main.go, line 39 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADYSg-C49un2-Y_0nY:-LAK0O--CnMVfpqgBqC-:bpg03f1) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/integration/main.go#L39)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

Why can't we use EdDSA here? (on review, because EdDSA for X.509 hasn't been published yet, perhaps...)
</blockquote></details>

Looking into this, will fix in next commits.

---

*[man/rainsd.md, line 78 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADaV3p4KuRLJWWf8kl:-LAK1J4x0QchHoFTsY-b:bvsdc5z) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/man/rainsd.md#L78)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

...to be continued?
</blockquote></details>

Still need to verify these but I added a short description for them so far.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/rains/76)*

**Comment by rayhaanj** [comment]
Review status: 24 of 31 files reviewed at latest revision, 6 unresolved discussions.

---

*[integration/main.go, line 1 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADZAOL4HotSSvg28iH:-LAMwz2r9t8SMcORXYhD:b42yp26) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/integration/main.go#L1)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

The basic organization of this file is good; I'd like to see if there are things we can pull out of this file for more modular testing later.
</blockquote></details>

Moved the generic stuff like saving keys to disk, probing ports and copying binaries into the `utils`package so that the main file reads more nicely.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/rains/76)*

**Comment by britram** [comment]
Reviewed 7 of 7 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[man/rainsd.md, line 78 at r5](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-LADaV3p4KuRLJWWf8kl:-LAmKU7g4MDxMHLrYijL:b-i473fl) ([raw file](https://github.com/netsec-ethz/rains/blob/2c7b4ee634b5da6e9e6265f0ed8639dd414f2169/man/rainsd.md#L78)):*
<details><summary><i>Previously, rayhaanj (Rayhaan Jaufeerally) wrote…</i></summary><blockquote>

Still need to verify these but I added a short description for them so far.
</blockquote></details>

OK. (I actually got confused by the commas at the end of each item; this is good...)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/rains/76)*

**Comment by britram** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/rains/76#-:-LAmKh3H3aD4fWaom_y2:bg7igk9)*

**Pull request merged**
