### PR TITLE
Use go's net package for address type

### PR DESCRIPTION
**Pull request by fehlmach**
replaced port and net.IP with net.TCPAddr
moved ConnInfo object to rainslib as it is also used in the client.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/25)

### CODE REVIEW

**Comment by klausman** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[rainslib/datamodel.go, line 643 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/25#-KlwaAliw2fxSUIErCjO:-KlwaAljsXl1cZWfGmpa:b-yrygpa) ([raw file](https://github.com/netsec-ethz/rains/blob/1d5ff2a1b939166f71433cf15815ded6767db896/rainslib/datamodel.go#L643)):*
> ```Go
> 		return c.TCPAddr.String()
> 	default:
> 		log.Warn("Not supported network address ")
> ```

nit: "Unsupported address type", also log the type (e.g. log.Warn(..., "type", `fmt.Sprintf("%+v", c.Type)`) Not 100% sure about `%+v` vs. `%T` here, feel free to experiment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/25)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/25#-:-KlwamWDcqGT0V2Hz8l9:bnfp4nl)*

**Comment by fehlmach** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[rainslib/datamodel.go, line 643 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/25#-KlwaAliw2fxSUIErCjO:-KlwdX8xLlYgtMsAllyz:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/1d5ff2a1b939166f71433cf15815ded6767db896/rainslib/datamodel.go#L643)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

nit: "Unsupported address type", also log the type (e.g. log.Warn(..., "type", `fmt.Sprintf("%+v", c.Type)`) Not 100% sure about `%+v` vs. `%T` here, feel free to experiment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/25)*

**Comment by britram** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[rainsd/serverUtil.go, line 129 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/25#-Klwf9hyQf7w8XAtquCj:-Klwf9hyQf7w8XAtquCk:bvq6kfn) ([raw file](https://github.com/netsec-ethz/rains/blob/3c48728d453348229ca3a82374936653ef658fdb/rainsd/serverUtil.go#L129)):*
> ```Go
> 	log.Warn("Not yet implemented CFE. return hard coded delegation address")
> 	tcpAddr := loadDefaultSeverAddrIntoConfig()
> 	tcpAddr.Port = tcpAddr.Port + 1
> ```

FYI: we should have some documentation as to which ports we're using and why.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/25)*

**Comment by britram** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/25#-:-KlwfjQamNSfgZcfytra:bnfp4nl)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[rainsd/serverUtil.go, line 129 at r2](https://reviewable.io:443/reviews/netsec-ethz/rains/25#-Klwf9hyQf7w8XAtquCj:-KlwgT85zP9Jrpzti4IO:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/3c48728d453348229ca3a82374936653ef658fdb/rainsd/serverUtil.go#L129)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

FYI: we should have some documentation as to which ports we're using and why.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/25)*

**Pull request merged**
