### PR TITLE
Basic Workflow

### PR DESCRIPTION
**Pull request by fehlmach**
Basic workflow works
generation of root key
loading of root key
publish assertions to server (via rainspub)
assertions' signatures are verified and added to cache
queries can be generated and send to the serer (via rainsdig)
server processes queries and answers accordingly (pos&neg)
answer is displayed in cmd line in simple format (rainsdig)

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/rains/10)

### CODE REVIEW

**Comment by klausman** [comment]
A few comments.

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[rainsd/switchboard.go, line 95 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJGM9Ljg3hhFCD4qSz:-KlJGM9MQviILDPNy1NJ:b-ujmotr) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/switchboard.go#L95)):*
> ```Go
> 	cert, err := tls.LoadX509KeyPair(Config.TLSCertificateFile, Config.TLSPrivateKeyFile)
> 	if err != nil {
> 		srvLogger.Warn("Path to CertificateFile or privateKeyFile might be invalid. Default values are used", "CertPath", Config.TLSCertificateFile, "KeyPath", Config.TLSPrivateKeyFile)
> ```

Log the error object here. Also, I am not sure we should carry on with the defaults. It sortof violates the principle of least surprise.

Instead the default filenames should be the defaults of some command line or config flag value and this error branch should return the error like the error branch below.

---

*[rainsd/config/rootZoneFile.txt, line 3 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJHQw1dtulQdt4WA6W:-KlJHQw2jOwUIoPbjPnQ:beka991) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/config/rootZoneFile.txt#L3)):*
> ```
> :Z: . . [
>             :A: @ [ :deleg: 1 25 10 ]
>             
> ```

Are these spaces strictly necessary?

---

*[rainsdig/rainsdig, line 0 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJHVLCpGDUyKk1qCt4:-KlJHVLCpGDUyKk1qCt5:bg0kgl8) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsdig/rainsdig#L0)):*
I think this file is here by accident.

---

*[rainslib/datamodel.go, line 445 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJHpxHI2lvyrhuR0Ze:-KlJHpxHI2lvyrhuR0Zf:bfdy2t) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainslib/datamodel.go#L445)):*
> ```Go
> 
> const (
> 	OTName        ObjectType = 1
> ```

You can change this enum to:

```
const ( 
  Unknown = iota // this is implicitly 0
  OTName
  OTIP6Addr
 ...
}
```


---

*[rainspub/rainspubUtil.go, line 30 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJN2TxXS8w0bDY5_9z:-KlJN2TxXS8w0bDY5_A-:b-wltewr) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainspub/rainspubUtil.go#L30)):*
> ```Go
> 		//FIXME CFE use a better source of randomness for the key generation
> 		var publicKey ed25519.PublicKey
> 		publicKey, zonePrivateKey, err = ed25519.GenerateKey(rand.New(rand.NewSource(time.Now().UnixNano())))
> ```

Just use `nil`:

https://github.com/golang/crypto/blob/master/ed25519/ed25519.go#L62

```
// GenerateKey generates a public/private key pair using entropy from rand.
// If rand is nil, crypto/rand.Reader will be used.
```

---

*[utils/keyCreation/keyCreation.go, line 20 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJPRZTyeBddCaDplFE:-KlJPRZUjIPkldo1xFlJ:b-c2luit) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/keyCreation/keyCreation.go#L20)):*
> ```Go
> //In case of root public key the assertion is self signed (zone=.)
> func CreateDelegationAssertion(context, zone string) error {
> 	//FIXME CFE change source of randomness
> ```

Again, just use nil.

---

*[utils/keyCreation/keyCreation.go, line 79 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJPbGCSa7ZG-AETeIO:-KlJPbGCSa7ZG-AETeIP:bdffzhu) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/keyCreation/keyCreation.go#L79)):*
> ```Go
> 	privateKeyEnc := make([]byte, hex.EncodedLen(len(privateKey)))
> 	hex.Encode(privateKeyEnc, privateKey)
> 	err := ioutil.WriteFile("tmp/private.key", privateKeyEnc, 0644)
> ```

These permissions are not good for a private key file. Use 0600 or at least 0640.

---

*[utils/keyCreation/keyCreation.go, line 106 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJPtbmx-0oLS9McYio:-KlJPtbnqXsKe7AOt5GZ:b7md7r9) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/keyCreation/keyCreation.go#L106)):*
> ```Go
> 	err = rainslib.Save(delegationPath, delegation)
> 	if err != nil {
> 		log.Error("Was not able to encode and store the delegation", "delegation", delegation)
> ```

Log the error object here.

---

*[utils/parser/rainsMsgParser.go, line 55 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJQ8KPg3hPiwJmVM1F:-KlJQ8KPg3hPiwJmVM1G:brduxjz) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/parser/rainsMsgParser.go#L55)):*
> ```Go
> 	}
> 	capabilities := msg[capability+5:]
> 	caps := []rainslib.Capability{}
> ```

The name `caps` is confusing if there also is `capabilities` in the same context.

---

*[utils/parser/rainsMsgParser.go, line 386 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJQXMxBN_YPIG8W7Ar:-KlJQXMxBN_YPIG8W7As:b-nycq3u) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/parser/rainsMsgParser.go#L386)):*
> ```Go
> 			pkType, err := strconv.Atoi(pkData[0])
> 			if err != nil {
> 				log.Warn("Was not able to parse the public key type", "type", pkData[0])
> ```

Log the error here.

---

*[utils/parser/rainsMsgParser.go, line 392 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJQZkyH110tm-QcVDP:-KlJQZkzst70t3Sj8I6J:b-nycq3u) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/parser/rainsMsgParser.go#L392)):*
> ```Go
> 				keyData, err := hex.DecodeString(pkData[1])
> 				if err != nil || len(keyData) != 32 {
> 					log.Warn("Object's value malformed.", "bytestring", od[1])
> ```

Log the error here.

---

*[utils/parser/rainsMsgParser.go, line 589 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJQk0UM9hwxBwqGZLM:-KlJQk0UM9hwxBwqGZLN:b-nf3knk) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/parser/rainsMsgParser.go#L589)):*
> ```Go
> 		sigData, err := hex.DecodeString(sig[sd+4:])
> 		if err != nil {
> 			return signatures, nil
> ```

Shouldn't this be `signatures, err` or `nil, err`?

---

*[utils/zoneFileParser/zoneFileParser.go, line 27 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJR-O6cmbkS50Hw2wC:-KlJR-O6cmbkS50Hw2wD:b-2vn9nu) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/zoneFileParser/zoneFileParser.go#L27)):*
> ```Go
> 	scanner.Scan()
> 	if scanner.Text() != ":Z:" {
> 		log.Warn("zoneFile malformed. It does not start with :Z:")
> ```

Maybe log the actual data seen here?

---

*[utils/zoneFileParser/zoneFileParser.go, line 33 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJR89P36D8jXvsGm3m:-KlJR89P36D8jXvsGm3n:bkvd5yr) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/zoneFileParser/zoneFileParser.go#L33)):*
> ```Go
> 	scanner.Scan()
> 	zone := scanner.Text()
> 	scanner.Scan() //scan [
> ```

Maybe add a check here whether `Text()` is actually `[` (or contains one, at least) and bail if it doesn't?

---

*[utils/zoneFileParser/zoneFileParser.go, line 52 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJRLdLdeMMZj57BNP7:-KlJRLdLdeMMZj57BNP8:b-d5173s) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/zoneFileParser/zoneFileParser.go#L52)):*
> ```Go
> 			return nil, fmt.Errorf("Expected a shard or assertion inside the zone but got=%s", scanner.Text())
> 		}
> 		scanner.Scan()
> ```

Annotate and/or check that this handles the `]`

---

*[utils/zoneFileParser/zoneFileParser.go, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJRRUASkikDfMGrcLK:-KlJRRUASkikDfMGrcLL:b2nreh6) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/zoneFileParser/zoneFileParser.go#L59)):*
> ```Go
> func parseShard(context, zone string, scanner *bufio.Scanner) ([]*rainslib.AssertionSection, error) {
> 	assertions := []*rainslib.AssertionSection{}
> 	scanner.Scan() //scans [
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-:-KlJSaSkV9bTa2CzG1_q:b-804dua)*

**Comment by britram** [comment]
Reviewed 8 of 28 files at r1.
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[rainsd/engine.go, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNTYSiXGNsAC2iXRbF:-KlNTYSiXGNsAC2iXRbG:bot2e3q) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/engine.go#L14)):*
> ```Go
> 
> //assertionCache contains a set of valid assertions where some of them might be expired.
> //An entry is marked as extrenal if it might be evicted by a RLU caching strategy.
> ```

FYI you mean "LRU" here

---

*[rainsd/engine.go, line 47 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNTlIlGOWw6EtNTx9D:-KlNTlIlGOWw6EtNTx9E:bfs6gxe) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/engine.go#L47)):*
> ```Go
> 	}
> 
> 	go reapVerify()
> ```

The fact that initializing the engine launches a goroutine as a side-effect makes sense, but should be well-documented.

---

*[rainsd/engine.go, line 351 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNVvJCxmMBQA7StsUc:-KlNVvJD4X1JHTNvJFxu:b-35i8uu) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/engine.go#L351)):*
> ```Go
> 
> //reapEngine deletes expired elements in the following caches: assertionCache, negAssertionCache, pendingQueries
> func reapEngine() {
> ```

Do we need a way to shut this goroutine down? 

---

*[rainsd/verify.go, line 53 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNWZgQ9fNVqmWD_tkS:-KlNWZgQ9fNVqmWD_tkT:brdix5h) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/verify.go#L53)):*
> ```Go
> 	}
> 
> 	go reapVerify()
> ```

This goroutine also gets launched in engine.go; is this intentional?

---

*[rainsd/config/rootZoneFile.txt, line 3 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJHQw1dtulQdt4WA6W:-KlNWpo6T2DxvSmwHWsx:bulnz22) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/config/rootZoneFile.txt#L3)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Are these spaces strictly necessary?
</blockquote></details>

We'd like to be able to use a tokenizer that separates on whitespace. So at least one of these spaces is strictly necessary. But this isn't Makefile or BIND zonefile, so the choice of additional spaces is purely stylistic. That said, since rainsdig will spit out zonefile-like output, we have a chance to influence "canonical" style. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/10)*

**Comment by britram** [comment]
Reviewed 10 of 28 files at r1.
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[rainspub/config/rainspub.conf, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNa7P7TirWaiv9ArIE:-KlNa7P7TirWaiv9ArIF:b-ylw50y) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainspub/config/rainspub.conf#L2)):*
> ```
> {
> "AssertionValidity": 86400000000000,
> ```

it seems slightly odd to me to do this in nanoseconds. don't seconds suffice?

---

*[server/config/rainspub.conf, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNaJL3bVsI-tCvKY2E:-KlNaJL3bVsI-tCvKY2F:b-s5ez3b) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/server/config/rainspub.conf#L2)):*
> ```
> {
> "AssertionValidity": 86400000000000,
> ```

nanoseconds?

---

*[utils/zoneFileParser/zoneFileParser.go, line 27 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJR-O6cmbkS50Hw2wC:-KlNaaq_sl9CRlX7cDWy:b-3ms7p8) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/zoneFileParser/zoneFileParser.go#L27)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Maybe log the actual data seen here?
</blockquote></details>

Parser error logging is (1) really difficult to get right but (2) crucial to keep from annoying the hell out of our users. Keep in mind you're the first user of this parser. :) I'd at least suggest keeping track of newlines so you can at least log which line is causing you trouble.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/10)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[rainsd/engine.go, line 14 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNTYSiXGNsAC2iXRbF:-KlOijR_5D7f3C5h60cE:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/engine.go#L14)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

FYI you mean "LRU" here
</blockquote></details>

Done.

---

*[rainsd/engine.go, line 47 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNTlIlGOWw6EtNTx9D:-KlOkYxCeQ3wkOlOIDd0:b-u125jl) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/engine.go#L47)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

The fact that initializing the engine launches a goroutine as a side-effect makes sense, but should be well-documented.
</blockquote></details>

The go routine should have started reapEngine()

---

*[rainsd/engine.go, line 351 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNVvJCxmMBQA7StsUc:-KlOj4YFRRp6TPBxRXCx:bkjlho9) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/engine.go#L351)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

Do we need a way to shut this goroutine down? 
</blockquote></details>

I don't think so because as long as the server is running we want to clean up the caches. When the server goes down then also all spawned go routines are terminated.

---

*[rainsd/verify.go, line 53 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNWZgQ9fNVqmWD_tkS:-KlOkT7YbaTNqHR7KE02:b-yw646y) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/verify.go#L53)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

This goroutine also gets launched in engine.go; is this intentional?
</blockquote></details>

No, it should only be launched in the verify.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/10)*

**Comment by fehlmach** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[rainsd/engine.go, line 47 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNTlIlGOWw6EtNTx9D:-KlSNBsgYsE65Ql5Es3z:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/engine.go#L47)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

The go routine should have started reapEngine()
</blockquote></details>

Done.

---

*[rainsd/switchboard.go, line 95 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJGM9Ljg3hhFCD4qSz:-KlSEv7yDVTc6uUVQi_W:b6isk4) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/switchboard.go#L95)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Log the error object here. Also, I am not sure we should carry on with the defaults. It sortof violates the principle of least surprise.

Instead the default filenames should be the defaults of some command line or config flag value and this error branch should return the error like the error branch below.
</blockquote></details>

I make a new issue for that.

---

*[rainsd/verify.go, line 53 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNWZgQ9fNVqmWD_tkS:-KlSNGTfyJNVCVWc1Z2t:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/verify.go#L53)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

No, it should only be launched in the verify.go
</blockquote></details>

Done.

---

*[rainsd/config/rootZoneFile.txt, line 3 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJHQw1dtulQdt4WA6W:-KlSFdxYmtSsz8AXZtqF:b-x8hea6) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsd/config/rootZoneFile.txt#L3)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

We'd like to be able to use a tokenizer that separates on whitespace. So at least one of these spaces is strictly necessary. But this isn't Makefile or BIND zonefile, so the choice of additional spaces is purely stylistic. That said, since rainsdig will spit out zonefile-like output, we have a chance to influence "canonical" style. 
</blockquote></details>

I leave it like this so far.

---

*[rainsdig/rainsdig, line  at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJHVLCpGDUyKk1qCt4:-KlSFsfffkQWaBtz3tXq:bb7s9xr) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainsdig/rainsdig#L)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

I think this file is here by accident.
</blockquote></details>

yep.

---

*[rainslib/datamodel.go, line 445 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJHpxHI2lvyrhuR0Ze:-KlSGKcT7bfSHO-Gs9gP:bvtypzv) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainslib/datamodel.go#L445)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

You can change this enum to:

```
const ( 
  Unknown = iota // this is implicitly 0
  OTName
  OTIP6Addr
 ...
}
</blockquote></details>

As we mentioned before, this mapping from type to number is explicitly defined in the rains protocol. We want to emphasize this by making it explicit, then reordering of names does not break the protocol.

---

*[rainspub/rainspubUtil.go, line 30 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJN2TxXS8w0bDY5_9z:-KlSHMmJdXQWe4ZiMCe5:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainspub/rainspubUtil.go#L30)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Just use `nil`:

https://github.com/golang/crypto/blob/master/ed25519/ed25519.go#L62

```
// GenerateKey generates a public/private key pair using entropy from rand.
// If rand is nil, crypto/rand.Reader will be used.
```
</blockquote></details>

Done.

---

*[rainspub/config/rainspub.conf, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNa7P7TirWaiv9ArIE:-KlSIqQzWEaz6A0Yxz0_:blg8ymt) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainspub/config/rainspub.conf#L2)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

it seems slightly odd to me to do this in nanoseconds. don't seconds suffice?
</blockquote></details>

I use json.unmarshal() to read this data directly into the config type. And time.Duration uses nanoseconds. I could instead read in a int64 and then explicitly transform this value into a time.Duration type. I add this point to the issue of getting ride of default values

---

*[server/config/rainspub.conf, line 2 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlNaJL3bVsI-tCvKY2E:-KlSJgniWYBo8EVq_JxV:bo6n6c1) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/server/config/rainspub.conf#L2)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

nanoseconds?
</blockquote></details>

same as above, bus this file is duplicated and gets removed

---

*[utils/keyCreation/keyCreation.go, line 20 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJPRZTyeBddCaDplFE:-KlSKFNpRWBCtenpTS6W:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/keyCreation/keyCreation.go#L20)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Again, just use nil.
</blockquote></details>

Done.

---

*[utils/keyCreation/keyCreation.go, line 79 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJPbGCSa7ZG-AETeIO:-KlSKX7JYR7c54zbNW4G:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/keyCreation/keyCreation.go#L79)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

These permissions are not good for a private key file. Use 0600 or at least 0640.
</blockquote></details>

Done.

---

*[utils/keyCreation/keyCreation.go, line 106 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJPtbmx-0oLS9McYio:-KlSKdDAkijJDNdG4Z83:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/keyCreation/keyCreation.go#L106)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Log the error object here.
</blockquote></details>

Done.

---

*[utils/parser/rainsMsgParser.go, line 55 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJQ8KPg3hPiwJmVM1F:-KlSKwYhYuLxj4menL_8:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/parser/rainsMsgParser.go#L55)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

The name `caps` is confusing if there also is `capabilities` in the same context.
</blockquote></details>

Done.

---

*[utils/parser/rainsMsgParser.go, line 386 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJQXMxBN_YPIG8W7Ar:-KlSL7V_GiQPgLxR0VMe:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/parser/rainsMsgParser.go#L386)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Log the error here.
</blockquote></details>

Done.

---

*[utils/parser/rainsMsgParser.go, line 392 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJQZkyH110tm-QcVDP:-KlSLArkqRrzB_CfJ4pc:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/parser/rainsMsgParser.go#L392)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Log the error here.
</blockquote></details>

Done.

---

*[utils/parser/rainsMsgParser.go, line 589 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJQk0UM9hwxBwqGZLM:-KlSLWpMlrZxe73pRry1:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/parser/rainsMsgParser.go#L589)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Shouldn't this be `signatures, err` or `nil, err`?
</blockquote></details>

Done.

---

*[utils/zoneFileParser/zoneFileParser.go, line 27 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJR-O6cmbkS50Hw2wC:-KlSLmTCRCTwherP42mc:bjg7f4y) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/zoneFileParser/zoneFileParser.go#L27)):*
<details><summary><i>Previously, britram (Brian Trammell) wrote…</i></summary><blockquote>

Parser error logging is (1) really difficult to get right but (2) crucial to keep from annoying the hell out of our users. Keep in mind you're the first user of this parser. :) I'd at least suggest keeping track of newlines so you can at least log which line is causing you trouble.
</blockquote></details>

I make an issue for that

---

*[utils/zoneFileParser/zoneFileParser.go, line 33 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJR89P36D8jXvsGm3m:-KlSMPAyeSPT35u7o4pz:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/zoneFileParser/zoneFileParser.go#L33)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Maybe add a check here whether `Text()` is actually `[` (or contains one, at least) and bail if it doesn't?
</blockquote></details>

Done.

---

*[utils/zoneFileParser/zoneFileParser.go, line 52 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJRLdLdeMMZj57BNP7:-KlSN2zoeKd0L2TwceGO:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/zoneFileParser/zoneFileParser.go#L52)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Annotate and/or check that this handles the `]`
</blockquote></details>

Done.

---

*[utils/zoneFileParser/zoneFileParser.go, line 59 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJRRUASkikDfMGrcLK:-KlSMSAWvykNnfQwAZuV:b-896fix) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/utils/zoneFileParser/zoneFileParser.go#L59)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/10)*
<!-- Sent from Reviewable.io -->

**Comment by britram** [comment]
:lgtm:

---

Reviewed 2 of 28 files at r1, 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-:-Kld93lhqJmCaEXH48Lj:bnfp4nl)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[rainslib/datamodel.go, line 445 at r1](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-KlJHpxHI2lvyrhuR0Ze:-KldEAIi1LSz6t7BF2xb:b-81nlyc) ([raw file](https://github.com/netsec-ethz/rains/blob/dcc27f2d237e0c98f4a28865f7b5faa8ab22df8f/rainslib/datamodel.go#L445)):*
<details><summary><i>Previously, fehlmach wrote…</i></summary><blockquote>

As we mentioned before, this mapping from type to number is explicitly defined in the rains protocol. We want to emphasize this by making it explicit, then reordering of names does not break the protocol.
</blockquote></details>

SGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/rains/10#-:-KldEYqGCYduQ3WBcMi2:bnfp4nl)*

**Pull request merged**
